const express = require('express');
const router = express.Router();
const { checkout,payForOrder,updateOrderToPaid,getMyOrders,getAdminDashboard } = require('../controllers/orderController');
const { protect, admin } = require('../middleware/authMiddleware');
router.post('/checkout', protect, checkout);
router.post('/:id/pay', protect, payForOrder);
router.post('/:id/update-to-paid', protect, updateOrderToPaid);
router.get('/my-orders', protect, getMyOrders);
router.get('/admin-dashboard', protect, admin, getAdminDashboard);
module.exports = router;
